version: "3.8"

services:
  ktor-api:
    build: .  # Build the image from the current directory (where Dockerfile resides)
    ports:
      - "9000:9000"  # Map container port 9000 to host port 9000 (adjust if needed)
    environment:
      # Database connection details (replace with actual values)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      # DB_PASSWORD: 1234  # Don't store password directly!

  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
      POSTGRES_PASSWORD: 1234  # Don't store password directly!
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a volume to persist database data
